### ISSUE TITLE
Scrolling and background issues on 4.0.0. Works on 3.6.0

### ISSUE THREAD

**Issue by madushans** [adamabdelhamed/PowerArgs#159] opened 2023-01-28 13:59 UTC
Version 4.0.0 seems to have some issues with background color, scrolling and terminal window size.

running a CLI on version 4.0.0 looks as below, where once the available space on the window is exhausted, instead of scrolling down, it seems to cut off. Running the command again seems to overwrite the last line or so.
Also the background color has some issues, where it doesnt blend with the transparency. (default Windows Terminal config)

![image](https://user-images.githubusercontent.com/2970078/215269625-b5d5e7b8-dbc5-4fec-8946-98769be5f3d3.png)

running the CLI repeatedly without scrolling.
![image](https://user-images.githubusercontent.com/2970078/215269909-ed9b1321-e458-48de-8cf1-98be0856d6ec.png)

Same code against PowerArgs v 3.6.0 looks as below. (it scrolls as expected, regardless of window size. I resized the window after running)

![image](https://user-images.githubusercontent.com/2970078/215269736-6c6672fa-8494-4c50-939e-2bd567223a0e.png)

---

Windows 11 22H2 build 22621.1105
Windows Terminal Version: 1.15.3466.0

`settings.json` from Windows Terminal (don't remember changing anything here, but I may have long time ago)
(Renamed to CSV coz github doesn't like attaching json for some reason.)
[settings.csv](https://github.com/adamabdelhamed/PowerArgs/files/10527402/settings.csv)

Same behavior is observed in cmd as well.

4.0.0

![image](https://user-images.githubusercontent.com/2970078/215270265-09b13e62-4c6b-44c6-8655-cdab26068070.png)

3.6.0
![image](https://user-images.githubusercontent.com/2970078/215270475-4c7d17ad-83ab-438b-a970-90b34fa4276f.png)

**Comment by adamabdelhamed** [comment] 2023-03-11 13:39
I'll be releasing a fix for the scrolling soon. I had another fix for the BG color issue, but unfortunately it doesn't seem to work. The issue is that when I read Console.BackgroundColor it doesn't reflect the actual color that is in Windows terminal. This might be because Windows terminal supports full RGB. The ConsoleString class within PowerArgs can also handle full RGB (when the terminal supports it), but I can't match the terminal background if I can't read it.

**Comment by adamabdelhamed** [comment] 2023-03-11 14:20
Fixed in 4.0.1 (except the colors)

**Closed by adamabdelhamed** 2023-03-11 14:20 UTC
Labels: bug
